# Auto-generated rename script — run from your project root
# Renames screenshots so filenames match what the README expects
Write-Host 'Starting renames...' -ForegroundColor Cyan

Rename-Item -Path "Screenshots\doc-08_ticket01-ssh-connection-from-powershell.png" -NewName "doc-07_ticket01-ssh-connection-from-powershell.png"
Rename-Item -Path "Screenshots\doc-09_ticket01-docker-installed-versions.png" -NewName "doc-08_ticket01-docker-installed-versions.png"
Rename-Item -Path "Screenshots\doc-10_ticket01-nano-installed-env-configured.png" -NewName "doc-09_ticket01-nano-installed-env-configured.png"
Rename-Item -Path "Screenshots\doc-11_ticket01-docker-compose-containers-running.png" -NewName "doc-10_ticket01-docker-compose-containers-running.png"
Rename-Item -Path "Screenshots\doc-12_ticket01-glpi-login-page-first-access.png" -NewName "doc-11_ticket01-glpi-login-page-first-access.png"
Rename-Item -Path "Screenshots\doc-13_ticket01-glpi-dashboard-first-login.png" -NewName "doc-12_ticket01-glpi-dashboard-first-login.png"
Rename-Item -Path "Screenshots\doc-15_ticket01-second-nic-detected.png" -NewName "doc-14_ticket01-second-nic-detected.png"
Rename-Item -Path "Screenshots\doc-16_ticket01-static-ip-applied.png" -NewName "doc-15_ticket01-static-ip-applied.png"
Rename-Item -Path "Screenshots\doc-17_ticket01-ping-dc01-success.png" -NewName "doc-16_ticket01-ping-dc01-success.png"
Rename-Item -Path "Screenshots\doc-18_dc01-service-accounts-ou-created.png" -NewName "doc-19_dc01-service-accounts-ou-created.png"
Rename-Item -Path "Screenshots\doc-19_dc01-svc-glpi-ldap-account-created.png" -NewName "doc-20_dc01-svc-glpi-ldap-account-created.png"
Rename-Item -Path "Screenshots\doc-20_glpi-ldap-directories-empty-list.png" -NewName "doc-17_glpi-ldap-directories-empty-list.png"
Rename-Item -Path "Screenshots\doc-22_dc01-ldap-signing-requirement-relaxed.png" -NewName "doc-24_dc01-ldap-signing-requirement-relaxed.png"
Rename-Item -Path "Screenshots\doc-23_glpi-ldap-test-success-after-signing-fix.png" -NewName "doc-25_glpi-ldap-test-success-after-signing-fix.png"
Rename-Item -Path "Screenshots\doc-25_glpi-ldap-import-users-selected.png" -NewName "doc-27_glpi-ldap-import-users-selected.png"
Rename-Item -Path "Screenshots\doc-26_glpi-users-import-confirmation.png" -NewName "doc-28_glpi-users-import-confirmation.png"
Rename-Item -Path "Screenshots\doc-27_glpi-users-list-post-import.png" -NewName "doc-29_glpi-users-list-post-import.png"
Rename-Item -Path "Screenshots\doc-28_glpi-ticket-categories-before.png" -NewName "doc-30_glpi-ticket-categories-before.png"
Rename-Item -Path "Screenshots\doc-29_glpi-ticket-categories-created.png" -NewName "doc-31_glpi-ticket-categories-created.png"
Rename-Item -Path "Screenshots\doc-30_glpi-all-nine-tickets-created.png" -NewName "doc-32_glpi-all-nine-tickets-created.png"
Rename-Item -Path "Screenshots\doc-31_glpi-ticket1-solution-and-closed.png" -NewName "doc-33_glpi-ticket1-solution-and-closed.png"
Rename-Item -Path "Screenshots\doc-32_glpi-tickets-mixed-status-final.png" -NewName "doc-34_glpi-tickets-mixed-status-final.png"
Rename-Item -Path "Screenshots\doc-33_glpi-computers-assets-added.png" -NewName "doc-36_glpi-computers-assets-added.png"
Rename-Item -Path "Screenshots\doc-34_glpi-ticket-linked-to-asset.png" -NewName "doc-37_glpi-ticket-linked-to-asset.png"
Rename-Item -Path "Screenshots\doc-41_dc01-lab-ca-certificate-properties-valid.png" -NewName "doc-40_dc01-lab-ca-certificate-properties-valid.png"
Rename-Item -Path "Screenshots\doc-42_ticket01-cert-pasted-correctly-in-nano.png" -NewName "doc-41_ticket01-cert-pasted-correctly-in-nano.png"
Rename-Item -Path "Screenshots\doc-43_ticket01-cert-verified-docker-ps-container-name.png" -NewName "doc-42_ticket01-cert-verified-docker-ps-container-name.png"
Rename-Item -Path "Screenshots\doc-44_ticket01-tls-cacert-configured-in-container.png" -NewName "doc-43_ticket01-tls-cacert-configured-in-container.png"
Rename-Item -Path "Screenshots\doc-45_glpi-ldaps-test-all-stages-passed.png" -NewName "doc-44_glpi-ldaps-test-all-stages-passed.png"
Rename-Item -Path "Screenshots\doc-46_ticket01-docker-compose-yml-clean-with-persistence.png" -NewName "doc-45_ticket01-docker-compose-yml-clean-with-persistence.png"
Rename-Item -Path "Screenshots\doc-47_ticket01-persistence-verified-after-full-rebuild.png" -NewName "doc-46_ticket01-persistence-verified-after-full-rebuild.png"
Rename-Item -Path "Screenshots\doc-48_glpi-ldaps-final-confirmation-with-persistence.png" -NewName "doc-47_glpi-ldaps-final-confirmation-with-persistence.png"
Rename-Item -Path "Troubleshooting\ts-05_ticket01-acceleration-settings-check.png" -NewName "ts-04_ticket01-acceleration-settings-check.png"
Rename-Item -Path "Troubleshooting\ts-06_ticket01-iso-file-properties.png" -NewName "ts-05_ticket01-iso-file-properties.png"
Rename-Item -Path "Troubleshooting\ts-07_host-performance-cpu-disk-check.png" -NewName "ts-06_host-performance-cpu-disk-check.png"
Rename-Item -Path "Troubleshooting\ts-08_ticket01-processor-count-reduced-to-1.png" -NewName "ts-07_ticket01-processor-count-reduced-to-1.png"
Rename-Item -Path "Troubleshooting\ts-09_ticket01-docker-permission-denied.png" -NewName "ts-08_ticket01-docker-permission-denied.png"
Rename-Item -Path "Troubleshooting\ts-10_ticket01-browser-connection-refused-port80.png" -NewName "ts-09_ticket01-browser-connection-refused-port80.png"
Rename-Item -Path "Troubleshooting\ts-11_ticket01-netplan-yaml-indentation-check.png" -NewName "ts-10_ticket01-netplan-yaml-indentation-check.png"
Rename-Item -Path "Troubleshooting\ts-16_glpi-ldaps-bind-failed-cant-contact-server.png" -NewName "ts-15_glpi-ldaps-bind-failed-cant-contact-server.png"
Rename-Item -Path "Troubleshooting\ts-17_ticket01-cert-pasted-directly-at-shell-prompt.png" -NewName "ts-16_ticket01-cert-pasted-directly-at-shell-prompt.png"
Rename-Item -Path "Troubleshooting\ts-18_ticket01-mkdir-permission-denied-non-root-exec.png" -NewName "ts-17_ticket01-mkdir-permission-denied-non-root-exec.png"
Rename-Item -Path "Troubleshooting\ts-19_ticket01-docker-command-not-found-inside-container.png" -NewName "ts-18_ticket01-docker-command-not-found-inside-container.png"
Rename-Item -Path "Troubleshooting\ts-20_glpi-ldaps-still-failing-after-cacert-added.png" -NewName "ts-19_glpi-ldaps-still-failing-after-cacert-added.png"
Rename-Item -Path "Troubleshooting\ts-21_ticket01-heredoc-paste-duplicated-content.png" -NewName "ts-20_ticket01-heredoc-paste-duplicated-content.png"

Write-Host 'Done. Run git status to confirm.' -ForegroundColor Green
